<div id="BBox" class="alert alert-info" style="font-family:courier;color:black;justify-content:left;">
<h1>Introduction to NumPy</h1>
<u>NumPy, short for Numerical Python </u>, is a fundamental library in Python used for <u>scientific computing and data analysis</u>. It provides a powerful array object, known as ndarray, which is a fast and flexible container for large datasets in Python. With its array-oriented computing capabilities, NumPy is essential for numerical operations and is a foundational library for many other scientific and machine learning libraries, such as SciPy, Pandas, and TensorFlow.
<br><br>
NumPy is known for its performance, enabling efficient numerical computations by leveraging optimized C and Fortran libraries, allowing operations on large datasets with minimal overhead. Its extensive functionality includes mathematical functions, linear algebra routines, Fourier transforms, and random number generation, making it a vital tool for data scientists and engineers alike.

<h2>Key Features of NumPy</h2>
<ul>
<li> <strong>N-dimensional Arrays: </strong>Provides support for multi-dimensional arrays (ndarrays) that facilitate efficient storage and manipulation of large datasets.</li>

<li><strong>Numerical Computation: </strong>Offers a comprehensive collection of mathematical functions for operations such as addition, subtraction, multiplication, division, and other statistical calculations.</li>

<li><strong>Broadcasting: </strong>Enables arithmetic operations on arrays of different shapes and sizes, extending smaller arrays to match the dimensions of larger arrays for seamless calculations.</li>

<li><strong>Indexing and Slicing: </strong>Supports advanced indexing and slicing techniques, allowing for easy data retrieval and manipulation.</li>

<li><strong>Linear Algebra: </strong>Provides built-in functions for matrix operations, such as dot products, matrix inversion, eigenvalues, and singular value decomposition.</li>

<li><strong>Random Number Generation: </strong>Contains a submodule for generating random numbers, which is useful for simulations, sampling, and initializing weights in machine learning models.</li>

<li><strong>Integration with Other Libraries: </strong>Serves as the foundational library for many other scientific libraries, enabling seamless integration and interoperability with frameworks like SciPy, Pandas, and TensorFlow.</li>

<li><strong>Data Type Flexibility: </strong>Supports a variety of data types, including integers, floats, and complex numbers, allowing for versatile data manipulation.</li>

<li><strong>Performance Optimization: </strong>Utilizes optimized C and Fortran libraries, leading to significant performance improvements for numerical computations compared to pure Python implementations.</li>

</ul>
</div>

In [2]:
#!pip install numpy

<div id="BBox" class="alert alert-info" style="font-family:courier;color:black;justify-content:left;">
<h1> `np.array()` </h1>

<strong>What It Is:</strong> <br>
Creates a NumPy array from a list or sequence of values, enabling efficient storage and operations.

<br>

<strong>How It’s Used:</strong><br>
arr = np.array([1, 2, 3, 4])

<strong> Why it is important</strong><br>
This function is the foundation of all NumPy operations, allowing data to be easily converted into an array format compatible with various mathematical operations.

</div>

In [3]:
import numpy as np

In [4]:
# 1D array
arr_1d = np.array([1, 2, 3, 4])
print("1D Array")
print(arr_1d)

# 2D array
arr_2d = np.array([[1, 2], [3, 4]])
print("2D Array")
print(arr_2d)


# 3D array
print("3D Array")
V3d = np.array([[[ 6, 1, 5], [ 9, 8, 6]],
                [[9, 0, 2], [2, 3, 9]]])

print(V3d)

1D Array
[1 2 3 4]
2D Array
[[1 2]
 [3 4]]
3D Array
[[[6 1 5]
  [9 8 6]]

 [[9 0 2]
  [2 3 9]]]


<div id="BBox" class="alert alert-info" style="font-family:courier;color:black;justify-content:left;">
<h1> np.zeros() </h1>

<strong>What It Is:</strong> <br>
Generates an array filled with zeros of a specified shape.

<br>

<strong>How It’s Used:</strong><br>
zeros = np.zeros((2, 3))

<strong> Why it is important</strong><br>
Useful for initializing arrays where the default value should be zero, such as matrices for model parameters.
</div>

In [5]:
zeros = np.zeros((2, 3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]]


<div id="BBox" class="alert alert-info" style="font-family:courier;color:black;justify-content:left;">
<h1> np.ones() </h1>

<strong>What It Is:</strong> <br>
Creates an array filled with ones of a specified shape.
<br>

<strong>How It’s Used:</strong><br>
ones = np.ones((2, 3))

<strong> Why it is important</strong><br>
Commonly used to initialize weights or matrices where a uniform value is needed. Ideal for creating bias vectors in ML models.
</div>

In [6]:
ones = np.ones((2, 3))
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]]


<div id="BBox" class="alert alert-info" style="font-family:courier;color:black;justify-content:left;">
<h1> np.full() </h1>

<strong>What It Is:</strong> <br>
Creates an array with a specified shape, filled with a constant value.
<br>

<strong>How It’s Used:</strong><br>
full_arr = np.full((2, 2), 7)

<strong> Why it is important</strong><br>
Helpful for creating arrays with a specific fill value for testing, validation, or initialization.
</div>

In [7]:
full_arr = np.full((2, 2), 7)
print(full_arr)

[[7 7]
 [7 7]]


<div id="BBox" class="alert alert-info" style="font-family:courier;color:black;justify-content:left;">
<h1> np.eye() </h1>

<strong>What It Is:</strong> <br>
Generates an identity matrix of specified size.
<br>

<strong>How It’s Used:</strong><br>
identity = np.eye(3)

<strong> Why it is important</strong><br>
Identity matrices are essential in linear algebra and are commonly used in ML algorithms involving transformations or matrix multiplications.
</div>

In [8]:
identity = np.eye(3)
print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


<div id="BBox" class="alert alert-info" style="font-family:courier;color:black;justify-content:left;">
<h1> np.arange() </h1>

<strong>What It Is:</strong> <br>
Creates an array with evenly spaced values within a specified range.
<br>

<strong>How It’s Used:</strong><br>
arr_range = np.arange(0, 10, 2)

<strong> Why it is important</strong><br>
Useful for generating sequences, like a range of indices or parameter values, in ML.
</div>

In [9]:
arr_range = np.arange(0, 10, 2)
print(arr_range)

[0 2 4 6 8]


<div id="BBox" class="alert alert-info" style="font-family:courier;color:black;justify-content:left;">
<h1> np.linespace() </h1>

<strong>What It Is:</strong> <br>
Generates an array with a specified number of evenly spaced values between two limits.
<br>

<strong>How It’s Used:</strong><br>
lin_space = np.linspace(0, 1, 5)

<strong> Why it is important</strong><br>
Commonly used for generating values in a specified interval, which is useful in interpolation, plotting, and data sampling.
</div>

In [10]:
lin_space = np.linspace(0, 1, 5)
print(lin_space)

[0.   0.25 0.5  0.75 1.  ]


<div id="BBox" class="alert alert-info" style="font-family:courier;color:black;justify-content:left;">
<h1> np.random.randn() </h1>

<strong>What It Is:</strong> <br>
Generates an array of random values from a standard normal distribution with a mean of 0 and a standard deviation of 1.

<br>

<strong>How It’s Used:</strong><br>
rand_normal = np.random.randn(5)

<strong> Why it is important</strong><br>
Frequently used for initializing weights in ML models due to the normal distribution’s properties.
</div>

In [11]:
rand_normal = np.random.randn(5)
print(rand_normal)

[-0.64866517  0.28624966 -1.30224616 -0.7412715   1.72324011]


<div id="BBox" class="alert alert-info" style="font-family:courier;color:black;justify-content:left;">
<h1> np.random.randint() </h1>

<strong>What It Is:</strong> <br>
Creates an array of random integers within a specified range.

<br>

<strong>How It’s Used:</strong><br>
rand_ints = np.random.randint(1, 10, (2, 3))

<strong> Why it is important</strong><br>
Used for generating random integers for classification, sampling, or creating index-based random values.
</div>

In [12]:
rand_ints = np.random.randint(1, 10, (2, 3)) #Start, end and then dimension
print(rand_ints)

[[2 6 5]
 [8 5 3]]


<div id="BBox" class="alert alert-info" style="font-family:courier;color:black;justify-content:left;">
<h1> Array Attributes </h1>
<ul>
<li><strong>ndarray.shape : </strong> Returns the shape of the array as a tuple of dimensions, representing the number of elements along each axis.</li>
<li><strong>ndarray.size :</strong> Provides the total number of elements in the array.</li>
<li><strong>ndarray.ndim : </strong>Returns the number of dimensions (axes) of the array.</li>
<li><strong>ndarray.dtype : </strong>Shows the data type of elements stored in the array.</li>
<li><strong>ndarray.itemsize : </strong>Returns the size in bytes of each element in the array.</li>
<li><strong>ndarray.nbytes : </strong>Shows the total number of bytes consumed by the elements of the array.</li>
<li><strong>ndarray.T : </strong>Provides the transpose of the array, swapping rows and columns in a 2D array.</li>
<li><strong>ndarray.flat : </strong>Provides a 1D iterator over all elements of the array.</li>
<li><strong>ndarray.reshape : </strong> Reshape array to the given dimension</li>
<li><strong>ndarray.concatenate : </strong> Join a sequence of arrays along an existing axis.</li>
<li><strong>ndarray.vstack : </strong> Stack arrays in sequence vertically (row wise).</li>
<li><strong>ndarray.hstack : </strong>Stack arrays in sequence horizontally (column wise).</li>
</ul>

</div>

In [23]:
# 1D array
arr_1d = np.array([1, 2, 3, 4])
temp = np.array([1, 2, 3, 4], dtype=np.int32)
print("1D Array")
print("Shape: ",arr_1d.shape)
print("Size: ",arr_1d.size)
print("Dimension: ",arr_1d.ndim)
print("Data Type: ",arr_1d.dtype)
print("Memory (bytes): ",temp.itemsize)
print("Memory (Bytes): ",temp.nbytes)

# # 2D array
# arr_2d = np.array([[1, 2], [3, 4]])
# print("2D Array")
# print(arr_2d)

print("---------------------------------------")
# 3D array
print("3D Array")
V3d = np.array([[[ 6, 1, 5], [ 9, 8, 6]],
                [[9, 0, 2], [2, 3, 9]]])

print("1D Array")
print("Shape: ",V3d.shape)
print("Size: ",V3d.size)
print("Dimension: ",V3d.ndim)
print("Data Type: ",V3d.dtype)

flat_iter = [x for x in V3d.flat]
print("Flat Array: ", flat_iter)

transposed = V3d.T
print("Transpose: ",transposed.shape)

reshaped_array = np.reshape(V3d, (3, 4)) # C-like index ordering
print("Reshaped Array: ",reshaped_array.shape)

print("---------------------------------------")
A = np.array([[1, 2, 3, 4, 5]])
B = np.array([[4, 5, 6, 7, 8]])
C= np.concatenate((A, B), axis=0)
print(C)
print(C.shape)
print("---------------------------------------")
A = np.array([[1, 2, 3, 4, 5]])
B = np.array([[4, 5, 6, 7, 8]])
D= np.concatenate((A, B), axis=1)
print(D)
print(D.shape)
print("---------------------------------------")
C = np.vstack((A,B))
print(C)
print(C.shape)
print("---------------------------------------")
D = np.hstack((A,B))
print(D)
print(D.shape)

1D Array
Shape:  (4,)
Size:  4
Dimension:  1
Data Type:  int32
Memory (bytes):  4
Memory (Bytes):  16
---------------------------------------
3D Array
1D Array
Shape:  (2, 2, 3)
Size:  12
Dimension:  3
Data Type:  int32
Flat Array:  [6, 1, 5, 9, 8, 6, 9, 0, 2, 2, 3, 9]
Transpose:  (3, 2, 2)
Reshaped Array:  (3, 4)
---------------------------------------
[[1 2 3 4 5]
 [4 5 6 7 8]]
(2, 5)
---------------------------------------
[[1 2 3 4 5 4 5 6 7 8]]
(1, 10)
---------------------------------------
[[1 2 3 4 5]
 [4 5 6 7 8]]
(2, 5)
---------------------------------------
[[1 2 3 4 5 4 5 6 7 8]]
(1, 10)
