<div id="BBox" class="alert alert-info" style="font-family:courier;color:black;justify-content:left;">
<h1> Linear Algebra Operations </h1>
NumPy's linear algebra module is a powerful component that provides a range of functions for performing advanced matrix operations essential in scientific computing, machine learning, and data science. With linear algebra routines, users can easily execute operations such as matrix multiplication, determinant calculations, matrix inversion, and solving systems of linear equations. The module includes functions to compute eigenvalues and eigenvectors, perform singular value decomposition (SVD), and calculate matrix norms, all of which are fundamental in areas like dimensionality reduction, feature transformation, and optimization. These operations are highly optimized for performance, enabling efficient computation even on large datasets. NumPy’s linear algebra functions also offer support for complex numbers, making them suitable for signal processing and other advanced mathematical applications. By using NumPy’s streamlined syntax and highly optimized routines, practitioners can handle complex linear transformations and decompositions with minimal effort, making it an invaluable tool for both practical and theoretical computations.
<ul>
<li><strong>np.dot : </strong> Computes the dot product of two arrays. If both arrays are 1-dimensional, it calculates the inner product; if they are 2-dimensional, it performs matrix multiplication.
</li>
<li><strong>np.linalg.inv :</strong> Computes the inverse of a square matrix, which is a matrix that, when multiplied by the original matrix, yields the identity matrix.
</li>
<li><strong>np.linalg.det : </strong>Calculates the determinant of a square matrix. The determinant is a scalar value that provides information about the matrix, such as whether it’s invertible.
</li>
<li><strong>np.linalg.eig : </strong>Computes the eigenvalues and eigenvectors of a square matrix. Eigenvalues describe the scaling factor of eigenvectors under linear transformations.
</li>
<li><strong>np.linalg.norm : </strong>Computes the norm (magnitude) of a vector or matrix, with options for different types of norms like L1, L2, etc.
</li>
<li><strong>np.outer : </strong>Computes the outer product of two vectors, resulting in a matrix.</li>
</ul>

</div>

In [1]:
import numpy as np

In [2]:
A = np.array([[1, 2], [3, 4]])
print(A)
print("--------------")
B = np.array([[5, 6], [7, 8]])
print(B)
result = np.dot(A, B)
print("------------")
print(result)

[[1 2]
 [3 4]]
--------------
[[5 6]
 [7 8]]
------------
[[19 22]
 [43 50]]


In [3]:
A = np.array([[1, 2], [3, 4]])
print(A)
print("--------------")
inverse = np.linalg.inv(A)
print(inverse)

[[1 2]
 [3 4]]
--------------
[[-2.   1. ]
 [ 1.5 -0.5]]


In [4]:
A = np.array([[1, 2], [3, 4]])
print(A)
print("---------------------")
determinant = np.linalg.det(A)
print(determinant)

[[1 2]
 [3 4]]
---------------------
-2.0000000000000004


In [5]:
A = np.array([[1, 2], [2, 3]])
print(A)
print("---------------------")
eigenvalues, eigenvectors = np.linalg.eig(A)
print(eigenvalues)
print(eigenvectors[0])
print(eigenvectors[1])

[[1 2]
 [2 3]]
---------------------
[-0.23606798  4.23606798]
[-0.85065081 -0.52573111]
[ 0.52573111 -0.85065081]


In [6]:
vector = np.array([3, 4])
print(vector)
print("-------------------")
norm = np.linalg.norm(vector)
print(norm)

[3 4]
-------------------
5.0


In [7]:
a = np.array([1, 2, 3])
print(a)
print("------------------")
b = np.array([4, 5])
print(b)
print("------------------")
outer_product = np.outer(a, b)
print(outer_product)

[1 2 3]
------------------
[4 5]
------------------
[[ 4  5]
 [ 8 10]
 [12 15]]
