<div id="BBox" class="alert alert-info" style="font-family:courier;color:black;justify-content:left;">
<h1> Statistics  Operations </h1>
<ul>
<li><strong>np.mean : </strong> Computes the average (arithmetic mean) of an array along a specified axis.
</li>
<li><strong>np.median :</strong> Calculates the median, which is the middle value in a sorted array.
</li>
<li><strong>np.std : </strong>Computes the standard deviation, which measures the spread or dispersion of data.
</li>
<li><strong>np.var : </strong>Computes the variance, which is the average of the squared differences from the mean.
</li>
<li><strong>np.min, np.max : </strong>`np.min()` returns the minimum value, and `np.max()` returns the maximum value in an array.
</li>
<li><strong>np.percentile : </strong>Computes the nth percentile of data along a specified axis.
</li>
<li><strong>np.quantile : </strong>Computes quantiles, similar to percentiles but expressed as decimal fractions (e.g., 0.25, 0.5, 0.75).
</li>
<li><strong>np.corrcoef : </strong>Computes the Pearson correlation coefficient matrix, which measures linear relationships between variables.
</li>
<li><strong>np.histogram : </strong>Counts the occurrences of non-negative integers in an array.

</li>
<li><strong>np.bincount : </strong>Computes the outer product of two vectors, resulting in a matrix.</li>
</ul>

</div>

In [2]:
import numpy as np

In [3]:
arr = np.array([1, 2, 3, 4, 5])
mean_value = np.mean(arr)
print(mean_value)

3.0


In [4]:
arr = np.array([1, 2, 3, 4, 5])
median_value = np.median(arr)
print(median_value)

3.0


In [5]:
arr = np.array([1, 2, 3, 4, 5])
std_dev = np.std(arr)
print(std_dev)

1.4142135623730951


In [6]:
arr = np.array([1, 2, 3, 4, 5])
variance = np.var(arr)
print(variance)

2.0


In [7]:
arr = np.array([1, 2, 3, 4, 5])
min_value = np.min(arr)
print(min_value)
max_value = np.max(arr)
print(max_value)

1
5


In [8]:
arr = np.array([1, 2, 3, 4, 5])
percentile_50 = np.percentile(arr, 50)
print(percentile_50)

3.0


In [9]:
arr = np.array([1, 2, 3, 4, 5])
quantile_25 = np.quantile(arr, 0.25)
print(quantile_25)

2.0


In [10]:
x = np.array([1, 2, 3, 4])
y = np.array([5, 6, 7, 8])
correlation = np.corrcoef(x, y)
print(correlation)

[[1. 1.]
 [1. 1.]]


In [13]:
arr = np.array([1, 2, 1, 4, 3, 3, 2])
histogram, bins = np.histogram(arr, bins=3)
print(histogram)
print(bins)

[2 2 3]
[1. 2. 3. 4.]


In [17]:
arr = np.array([1, 2, 1, 3, 2, 1])
counts = np.bincount(arr)
print(counts)

[0 3 2 1]
